### ISSUE TITLE
Sim version incorrect

### ISSUE THREAD

**Issue by phet-steele** [phetsims/molecule-shapes#112]
Both molecule shapes and basics don't have the correct version information shown in the about dialogue and the browser tabs (should be 1.0.0-rc.1):

regular:
![img_0004](https://cloud.githubusercontent.com/assets/5863899/6379246/0d5125c2-bcee-11e4-814c-f249454e651b.PNG)

basics:
![img_0005](https://cloud.githubusercontent.com/assets/5863899/6379257/1b4fa28e-bcee-11e4-961b-42bdb6ed103e.PNG)

**Comment by phet-steele** [comment]
Also happening in iFrames

**Comment by jonathanolson** [comment]
I'm not sure exactly the combination of things I did wrong (because I was pretty sure about updating version.js before the deployment), because the commit tagged in dependencies.json is BEFORE I put accessibility behind a query parameter, but that is present in the deployed sim.

I'll make sure the version is set up correctly for the actual release.

**Comment by jonathanolson** [comment]
Fixed in RC.
