### ISSUE TITLE
Safari 8 performance extremely affected when using long string test

### ISSUE THREAD

**Issue by bryo5363** [phetsims/molecule-shapes#130]
I followed the request to perform the string test and only noticed affected performance on Safari 8 for OSX 10.10.3. 

Steps to reproduce
1) use an extremely long String for the string Test
2) open sim
3) turn on projector mode
4) go full screen
the performance will be severely affected

If the string is very long, the simulation will not even open. For Instance I used 
http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.1.0-rc.1/molecule-shapes_en.html?stringTest=WowThisIsSuchALongStringIReallyHopeThisSimulationDoesNotCrashButThankfullyICanAlwaysMakeTheseDarnStringsLonger

and I could not get the simulation to open

**Comment by samreid** [comment]
I reproduced the problem on my OS X Chrome.  Uncaught RangeError: Maximum call stack size exceeded

**Comment by jonathanolson** [comment]
Looks like a Panel updateBackground loop.

**Comment by samreid** [comment]
@jbphet volunteered to look into it.  Call on @samreid if you would like assistance.

**Comment by jbphet** [comment]
I've dug into this a bit, and the stack is getting quite deep in a call that originates from Panel.updateBackground, which triggers a change of the bounds, which triggers another updateBackground call, and apparently it starts recursing.  I'll try to figure out why this doesn't happen all the time, but thought I'd note that this ticket is likely related: https://github.com/phetsims/sun/issues/110.

**Comment by jbphet** [comment]
The problem is that the bounds are oscillating as the panel is being set up.  There is a comment in Panel.updateBackground() that says:

```js
   // Prevent oscillation and stack overflow due to numerical imprecision, see https://github.com/phetsims/sun/issues/110
```

But, if the bounds are printed before each update, here is a sample of what is seen:

>Panel.js?bust=1437774226583:96 content bounds changed: [x (352.8409733509475,505.46229369450714),y:(0,146)]
>Panel.js?bust=1437774226583:96 content bounds changed: [x:(352.8409733509474,505.462293694507),y:(0,146)]
>Panel.js?bust=1437774226583:96 content bounds changed: [x:(352.8409733509475,505.46229369450714),y:(0,146)]
>Panel.js?bust=1437774226583:96 content bounds changed: [x:(352.8409733509474,505.462293694507),y:(0,146)]
>Panel.js?bust=1437774226583:96 content bounds changed: [x:(352.8409733509475,505.46229369450714),y:(0,146)]

It would appear that the previous attempt to control oscillation didn't work, at least not in all circumstances.

**Comment by jbphet** [comment]
As an experiment, I removed the numerical precision test in the updateBackground function in Panel.js and instead added a flag to prevent recursive updates in updateBackground.  This seems to work, i.e. the sim doesn't crash and we don't end up with deep call stacks.  It's a bit hokey, but perhaps no more hokey than the current approach, and my guess is that this may improve performance for all users of this type.  I'll continue to look for alternatives, but this appears promising.

**Comment by jbphet** [comment]
I added a counter to measure just how deep the recursion goes if it isn't explicitly prevented as described in the previous comment.  This counter was incremented at the top of the Panel.js updateBackground function, logged to the console, and then decremented when exiting the function.  With normal strings, the depth reaches 3 when launching Molecule Shapes.  I tried this on several other sims, and 3 seems like the max.  In some cases, 2 was the max.  In the test with the very long string, the depth reached 3206 before the call stack size was exceeded and the sim crashed.

I don't know why the long string behaves so much differently, but it seems to me like we're asking for trouble if we have a listener on bounds changes and we call an update function that can itself change those bounds unless we explicitly prevent recursion.  I'm going to go ahead and push the change that uses a flag to prevent recursion instead of checking numerical precision.  I'll assign to @samreid to review and to see if he has a better idea.

**Comment by jbphet** [comment]
By the way, I tested this on several simulations that use panels after making the change and saw no issues.

**Comment by samreid** [comment]
I reverted Panel.js to sun/cec7fc906bdb209ba0938760f2e60eb25a59912d and reproduced the error.  After updating to @jbphet version, the problem is gone.

I understand the strategy @jbphet employed in the fix and it seems straightforward to me, but I am wondering when a secondary (recursive) update would have been triggered--how can we be certain that it was a small/insignificant change?

Also, I think it would be best for @jonathanolson to review this once he has time.  He was familiar with the previous issue in https://github.com/phetsims/sun/issues/110 and would be great if he can look for issues with this revision.

**Comment by jbphet** [comment]
I had the same question @samreid, i.e. is there ever a legitimate time to have updateBackground() called recursively?  In other words, could preventing recursion in calls to updateBackground() cause issues with panel layout?  My opinion on this is that it doesn't seem like a good application of the technique of recursion.  It's generally a bit tricky to use this technique correctly, and there always needs to be a decisive "end condition" to unwind the recursion, and I don't think we have that here.

Having said that, there are two alternatives that I can think of that may also be solutions to this issue:
+ Keep a record of the previous content bounds and only call updateBackground() if the width or height of the content changes
+ Keep a record of the previous content bounds and only call updateBackground() if the bounds change by some amount considered to be "significant", such as one of the values changes more than 1E-6.

**Comment by jbphet** [comment]
I tried the approach where updateBackground() was only called when the width or height of the content changes, but it doesn't work.  It appears that changing the position of the content (as is done in the updateBackground function) affects its size a tiny bit.  @jonathanolson may want to have a look at this, since it doesn't seem like correct behavior for Scenery, but it may just be floating point inaccuracies that can't easily be avoided.

I cleaned up the recursion prevention code a little, but left the functionality essentially the same.  @jonathanolson can close if he finds this solution acceptable.

There is still an unanswered question about why this only occurs with long strings, and @jonathanolson may wish to delve into this.

**Comment by jbphet** [comment]
I just discussed this with @jonathanolson, and he said that the issue is caused by rounding errors and there isn't much that could be done in Scenery to prevent it.  He feels that the flag for preventing recursion seems like a fine approach.  Closing.
