### ISSUE TITLE
Color of atoms in molecule hard to distinguish

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#153]
For https://github.com/phetsims/QA/issues/280
I noticed that many of the central atoms are hard to tell apart from the surrounding atoms.  This is particularly true if colorblindness is taken into account.  I was looking at MS:B.  
Normal View
![notevencolorblind](https://user-images.githubusercontent.com/41024075/52825239-2b786f80-3079-11e9-84c6-3dafd5547f3b.jpg)
Colorblind Filter
![colorblind](https://user-images.githubusercontent.com/41024075/52825247-33d0aa80-3079-11e9-807c-c78d874f69f9.jpg)

**Comment by arouinfar** [comment]
Thanks @KatieWoe! I checked with @jonathanolson and this sim is using nitroglycerin for the various atom colors (https://github.com/phetsims/nitroglycerin/blob/master/js/Element.js#L71-L87).

```js

  Element.Ar = new Element( 'Ar', 97, 188, null, 39.948, '#FFAFAF' );
  Element.B = new Element( 'B', 85, 192, 2.04, 10.811, 'rgb(255,170,119)' ); // peach/salmon colored, CPK coloring
  Element.Be = new Element( 'Be', 105, 153, 1.57, 9.012182, '#c2ff00' ); // beryllium
  Element.Br = new Element( 'Br', 114, 185, 2.96, 79.904, 'rgb(190,30,20)' ); // brown
  Element.C = new Element( 'C', 77, 170, 2.55, 12.0107, 'rgb(178,178,178)' );
  Element.Cl = new Element( 'Cl', 100, 175, 3.16, 35.4527, 'rgb(153,242,57)' );
  Element.F = new Element( 'F', 72, 147, 3.98, 18.9984032, 'rgb(247,255,74)' );
  Element.H = new Element( 'H', 37, 120, 2.20, 1.00794, '#ffffff' );
  Element.I = new Element( 'I', 133, 198, 2.66, 126.90447, '#940094' ); // dark violet, CPK coloring
  Element.N = new Element( 'N', 75, 155, 3.04, 14.00674, '#0000ff' );
  Element.Ne = new Element( 'Ne', 69, 154, null, 20.1797, '#1AFFFB' );
  Element.O = new Element( 'O', 73, 152, 3.44, 15.9994, PhetColorScheme.RED_COLORBLIND );
  Element.P = new Element( 'P', 110, 180, 2.19, 30.973762, 'rgb(255,128,0)' );
  Element.S = new Element( 'S', 103, 180, 2.58, 32.066, 'rgb(212,181,59)' );
  Element.Si = new Element( 'Si', 118, 210, 1.90, 28.0855, 'rgb(240,200,160)' ); // tan, Jmol coloring listed from https://secure.wikimedia.org/wikipedia/en/wiki/CPK_coloring
  Element.Sn = new Element( 'Sn', 145, 217, 1.96, 118.710, '#668080' ); // tin
  Element.Xe = new Element( 'Xe', 108, 216, 2.60, 131.293, '#429eb0' );
```
These colors appear to come from [CPK coloring or Jmol](https://en.wikipedia.org/wiki/CPK_coloring#Modern_variants), but there are some combinations which have pretty poor contrast for various forms of colorblindness. 

I can tweak the colors a bit to improve the colorblind contrast, but that should be done in nitroglycerin. Leaving self-assigned until that issue is opened.

**Comment by arouinfar** [comment]
See the above nitroglycerin issue.
