### ISSUE TITLE
Rotation of outer lone pairs

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#158]
For https://github.com/phetsims/QA/issues/279.  Very minor.  Appears in published version
When switching between the real and model versions of a molecule any outer lone pairs may rotate.  This seems to occur when switching from model to real.
To Reproduce:
1. Go to the real molecule screen
2. Go to options and activate the outer lone pairs
3. Go to CO2 (others will sometimes work, this seems most consistent)
4. Switch between the real and model radio buttons.  Observe behavior

![twisting](https://user-images.githubusercontent.com/41024075/52975708-bf9d4c00-3383-11e9-9958-b0a958673852.gif)

**Comment by arouinfar** [comment]
Nice observation @KatieWoe. This definitely looks a bit strange to me, but I think the rotation is occurring because the relative angle of the lone pairs is different.

Here's an alternative view of Model. I'm not sure why the angle between the external lone pairs is a bit variable.
<img src="https://user-images.githubusercontent.com/8419308/52980021-69d19f80-3395-11e9-8231-79935da8c048.png" width=300><img src="https://user-images.githubusercontent.com/8419308/52980094-c0d77480-3395-11e9-84d7-79a84cf364ec.png" width=300>

@jonathanolsondo you know what's going on here?

**Comment by jonathanolson** [comment]
I don't recall the exact reason, but I believe it was known and was too minor to handle before.

I think it's due to how the real molecule data is initialized.

**Comment by arouinfar** [comment]
Thanks @jonathanolson. I would agree it's still pretty minor, so I'll close as `type:wontfix`.
