### ISSUE TITLE
Molecule in screen selection and boded atoms in model screen disappears

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#161]
**Device**
Dirac
**OS**
10.11.6 and 10.12.6 (and 10.10 but this browser is not supported there)
**Browser**
Firefox
**Problem Description**
For https://github.com/phetsims/QA/issues/279 and https://github.com/phetsims/QA/issues/280
On the home screen and in the nav bar of the sim screens, the Real Molecules image is missing the ball and stick molecule, and only has the elements' letters.  webgl=false seems to bring the image back.
**Steps to reproduce:**
1. Go to Mac OS 10.11.6 firefox
2. Look at image for real molecules

**Screenshot**
![molecule shapes_ basics screenshot-1 1](https://user-images.githubusercontent.com/41024075/53254644-055a5d00-3681-11e9-8fb8-c6db355f6e51.png)

**Comment by KatieWoe** [comment]
This also seems to be there in the published version.

**Comment by KatieWoe** [comment]
The double and triple bonded atom selections on the model screen are also invisible @jonathanolson

**Comment by KatieWoe** [comment]
If you use showPointerAreas the boded atoms seem to be shifted out of their clickable area.

**Comment by KatieWoe** [comment]
I thought there may be a problem with the device, but I checked 10.11 on Magnus and it shows the problem as well.

**Comment by jonathanolson** [comment]
I've spent a lot of time tracking this down and looking for solutions, but I'm stuck since this looks like a browser OR three.js bug that happens when a WebGL context is reused. This means that only the 1st screen icon works, or only the 1st set of bond label icons work, since those used shared contexts. Unfortunately, just using more contexts isn't an option currently, since browsers like to "dump" older contexts when you create a bunch (so it could cause the main display's context to stop working). I'm not finding any particular workarounds yet, so given the contortions that would potentially be needed, I've reached the point where I would personally leave it as will-not-fix.

@ariel-phet thoughts?

**Comment by jonathanolson** [comment]
Patched on master and RCs to downgrade Firefox OS X 10.10-10.13 to Canvas. @KatieWoe can you check the behavior on master with Dirac?

**Comment by KatieWoe** [comment]
Tested all browsers on 10.10, 10.11, and 10.12 on Dirac.  No problems seen.

**Comment by jonathanolson** [comment]
Since this is worked around, marking as fixed-pending-testing.

**Comment by KatieWoe** [comment]
@jonathanolson this fix seems to have only been applied to Molecule Shapes Basics.  It still happens on Molecule Shapes

**Comment by jonathanolson** [comment]
Applied to Molecule Shapes, created rc.3 at https://phet-dev.colorado.edu/html/molecule-shapes/1.2.0-rc.3/phet/molecule-shapes_en_phet.html. Should I update the RC issue or create another?

**Comment by KatieWoe** [comment]
Haven't gotten too far, so update the rc and leave a comment saying you did that

**Comment by KatieWoe** [comment]
Looks fixed in that rc.3
