### ISSUE TITLE
Lone pairs can reappear

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#165]
For https://github.com/phetsims/QA/issues/301
Silly thing I noticed that is present in the published version and likely doesn't matter.  If you add a lone pair while building a molecule and click to hide them, you can make them visible again without selecting that box again.  To do this, get rid of the hidden lone pairs, then add one back.  Ignore the string Test in this gif.
![reappearing](https://user-images.githubusercontent.com/41024075/55181328-14856c80-5151-11e9-9c5f-008e2b80e242.gif)

**Comment by KatieWoe** [comment]
Does not seem to happen on the second screen

**Comment by kathy-phet** [comment]
I reviewed the behavior - and this actually seems like a design choice. I think we didn't want people to add lone pairs without being able to realize they were doing it, so we make it make them visible during the add process. 

So I don't think this is a bug. 

It won't happen on the second screen because you cannot add lone pairs.

**Comment by KatieWoe** [comment]
Sounds good.  Closing
