### ISSUE TITLE
Ability to rotate molecule by clicking anywhere on screen

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/molecule-shapes#197]
**Test device**
Dell 

**Operating System**
Windows 10

**Browser**
Chrome

**Problem description**
https://github.com/phetsims/qa/issues/715
https://github.com/phetsims/qa/issues/716

With the query parameter, showPointerAreas, it looks like the user should only be able to rotate the molecule by grabbing onto a terminal atom or lone pair (red highlights). However, if I click and drag on other areas of the screen, the molecule will rotate. I wasn't sure if that was intentional or not.

**Visuals**

![rotateanywhere](https://user-images.githubusercontent.com/87318828/139351841-6389e3ee-7034-4017-8544-be446cb9f120.gif)

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Molecule Shapes‬
URL: https://phet-dev.colorado.edu/html/molecule-shapes/1.4.0-dev.1/phet/molecule-shapes_all_phet.html?showPointerAreas
Version: 1.4.0-dev.1 2021-10-07 21:09:50 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
Language: en-US
Window: 1440x690
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi. I think this is intentional behavior. Dragging the background rotates the molecule as a whole without temporarily altering bond angles. Grabbing the atoms will also rotate the molecule, but the user also temporarily alters the bond angle.

In general, there are limitations to what `showPointerAreas` will display, so there may sometimes be a mismatch between the visuals and the sim behavior. I don't think there's anything that needs to be done here, so closing.
