### ISSUE TITLE
Metacog wrapper recorded wrong behavior

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#208]
For https://github.com/phetsims/qa/issues/745
When recording the sim on iPadOS 15.1 with metacog, I went into options and turned on some options such as lone pairs. When watching the playback, a screenshot was downloaded instead.

**Comment by KatieWoe** [comment]
Watching the playback, I think I know what happened. On iPad, there are three things in the PhET Menu: Options, Screenshot, and About. On computer (where I was watching back, there is a forth (Full Screen). So when I clicked Options on iPad, it corresponded to where Screenshot is on other platforms.

**Comment by jonathanolson** [comment]
Ahhh, presumably we'd need to include this metadata for playback to work. I also recall that we'd want to include platform details, font size metrics, etc.

@samreid thoughts?

**Comment by samreid** [comment]
There is generally a constraint that you are supposed to try to watch the playback on a similar platform to where it was recorded.  @zepumph do we have anything beyond this?

**Comment by KatieWoe** [comment]
I thought that the reason for the metadata testing on iPad was because the files can't be stored and used by the playback wrapper on the iPad, so it has to be watched on a computer?

**Comment by zepumph** [comment]
Hmm, In general @samreid communicated our philosophy thus far (playback should occur on the device that it was recorded on). It is infeasible to expect that we can generally cover every single possible discrepancy between two different runtimes of a sim. That said, this specific bug seems like something we should fix since it is for a common recording device that doesn't support the playback wrapper to my knowledge. And THAT said, it doesn't seem trivial, and so even if we don't just write it off as a won't-fix, it still may not be high enough priority to fix it. To me this really comes back to how important the playback WRAPPER is. Perhaps we should ask designers.

**Comment by samreid** [comment]
We dropped support for playing back input events and are moving toward state-based playbacks.  So I don't think work is warranted for this issue.  Closing.
