### ISSUE TITLE
Lone Pair panel doesn't disappear when lonePairNode.visibleProperty is false 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/molecule-shapes#243]
**Test device**
MacBook Air M1 chip

**Operating System**
13.2.1

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/905, when `moleculeShapes.modelScreen.view.lonePairPanel.lonePairNode.visibleProperty` is set to false, the Lone Pair panel remains even though it is empty. Shouldn't it disappear like the other panels do when the visible properties for everything in them are set to false?

**Visuals**
<img width="786" alt="Screenshot 2023-02-22 at 1 33 35 PM" src="https://user-images.githubusercontent.com/87318828/220725434-76a9562b-67bd-4e9b-ad88-5a4f49cc838c.png">

**Comment by arouinfar** [comment]
Thanks for reporting this inconsistency @Nancy-Salpepi. 

I don't think it's critical for panels to disappear automatically, and sometimes there are circumstances that prevent it from happening, such as https://github.com/phetsims/circuit-construction-kit-common/issues/939. Not sure if there are extenuating circumstances here, or if it was simply an oversight. 

That said, `moleculeShapes.modelScreen.view.lonePairPanel.lonePairNode.visibleProperty` is purposely not featured and we recommend that clients hide parents rather than individual children in the PhET-iO Guide. I am fine with closing this as wont-fix.

**Comment by jonathanolson** [comment]
I believe this should be fixed in master, and patched on the release branches. @Nancy-Salpepi can you verify?

**Comment by Nancy-Salpepi** [comment]
The lone pair panel now disappears. Thanks JO 🙂.

**Comment by jonathanolson** [comment]
Please close after verifying!

**Comment by Nancy-Salpepi** [comment]
This looks good in rc.2. Closing.

**Comment by Nancy-Salpepi** [comment]
Hey sorry. I have to reopen. 
If I set lonePairNode.visibleProperty to false, the panel disappears. If I change locale and launch the sim, it doesn't load. Here are the errors in the console:
<img width="410" alt="Screenshot 2023-03-02 at 9 26 44 PM" src="https://user-images.githubusercontent.com/87318828/222616542-8077434a-e106-44ac-9ef2-b29822c4aee9.png">

**Comment by jonathanolson** [comment]
I believe I've fixed this in master and the branches. Can you verify on master?

**Comment by Nancy-Salpepi** [comment]
This looks fixed in master (and I verified that it doesn't happen with other panels).

**Comment by zepumph** [comment]
Awesome. Thanks @Nancy-Salpepi for the quick turnaround.

**Comment by KatieWoe** [comment]
Looks good in rc.3
