### ISSUE TITLE
document tests

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-shapes#67]
Looks like there are some tests in js/tests/. Documented how to run the tests, how to maintain the tests, limitations, and anything else that may be necessary to properly maintain the tests and sim.

**Comment by jonathanolson** [comment]
I've added more documentation for the tests, and README.md for each tests directory following the conventions.

I'm really not sure what additional levels of documentation you were hoping for. For instance, each sim has a <sim>_en.html at the root, a js/version.js, etc. In those files, there is no documentation on how to run them (for HTML files), how to maintain them (no info in version.js about incrementing, no info in sim HTML for how to update when dependencies are added), or limitations (seems very general). I'm hesitant to manually add extensive documentation to a commonly-used pattern when it makes more sense to add to something like the PhET Development Overview (Google doc), and I'm happy to do that.

If it helps, a brief summary is below (can copy to wherever is convenient):
# Usage of Unit Tests
After making changes in one of the repos with unit tests, run the unit tests afterwards to see if anything is broken. I highly recommend checking "Hide passed tests", and wait until all tests are complete (it may pause at 0 tests complete at the start).
# Maintenance
unit-test.html and playground.html should be updated to point to new library versions when simulations are moved over (e.g. jquery version upgrade).
# Adding Unit Tests
If you want to add a test, add it to one of the tests/qunit/js/* files that have a QUnit module( '...' ) declaration, and read the QUnit tutorials to understand how it works. You can add new files with more tests by creating the file and referencing it in tests/qunit/js/unit-tests.js (whose purpose is to load those files).
# Namespaces for Unit Tests and Playground
Each unit-tests.html makes certain namespaces global (e.g. Scenery's makes window.scenery/kite/dot/axon/core for Scenery/Kite/Dot/Axon/phet-core respectively). Since unit tests don't use require.js directly (for Scenery/Kite/Dot they need to work with the standalone built-library versions), the namespaces are used to access types. For instance, "new scenery.Rectangle( ... )" is used.
# Playground
To make code available in the console, check the 'main' file used by the playground and add a reference there. For instance, Scenery's playground.html loads 'main' as the first array argument to the inner require() statement, and saves it to window.scenery. In require.js-speak, this sets the returned value of js/main.js to window.scenery, and in Scenery's specific case it returns the library namespace used in all unit tests. In addition, the same namespaces for unit tests are used.

**Comment by pixelzoom** [comment]
> I'm really not sure what additional levels of documentation you were hoping for. 

I was looking for a sentence or two about what the tests are testing. For example, model.js: I would expect this to unit the test the sim model, but it looks like tests for a math library. 

> I'm hesitant to manually add extensive documentation to a commonly-used pattern 

Commonly used? There are very few sims (or common repos) that have unit tests, and you're developing your own pattern. Help the rest of us understand what you're doing and maybe we'll adopt it.

> If it helps, a brief summary is below (can copy to wherever is convenient):

The "brief summary" above looks useful, recommend adding it to tests/README.md.

**Comment by jonathanolson** [comment]
> The "brief summary" above looks useful, recommend adding it to tests/README.md.

It was already a pain to update the loaded*Configs across 8 repos. I'd really like to avoid updating documentation copy-pasted in 8 places, and maybe that's a sign that the unit test code should be separated into a repo (chipper or a new one) and repos create a stub? Or just document it in one place?

If you disagree, let me know and I can copy-paste the documentation into each place.

Additionally, made f1e1e85c5a1a14c94dec443858f3b9f25b36d334 for model.js => fastmath.js

**Comment by pixelzoom** [comment]
8 places?... I thought we're talking about molecules-shapes/tests/README.md.

**Comment by pixelzoom** [comment]
Maybe these are 7 other test directories, in other repos, where you think this should be added?

Honestly, I don't care where you put it. But the information on how you're doing unit tests currently lives in your head and in this issue. I'm suggesting that it should live somewhere that's useful to the reset of the development team.  Maybe we should discuss at a developer meeting.

**Comment by jonathanolson** [comment]
Added to the PhET Development Overview (Google doc), under the "Utilities and Instrumentation for Development and Testing" section that already existed.

**Comment by pixelzoom** [comment]
Bueno. Closing.
